version: '3.7'

services:
  # tikv_cluster:
  #   container_name: tikv_cluster
  #   image: tikv_cluster_slim
  #   build:
  #     context: .
  #     target: tikv-slim
  #     dockerfile: tikv.dockerfile
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: 500M
  #   healthcheck:
  #     test: curl --fail http://tikv_cluster:2379/pd/api/v1/health
  #     interval: 15s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 0s
  #   volumes:
  #     - tikv_cluster:/home/tikv/.tiup/data/tikv_cluster
  #   ports:
  #     - 2379:2379
  #     - 9090:9090
  #     - 3000:3000

  surrealdb:
    container_name: surrealdb
    image: docker.io/surrealdb/surrealdb:1.0.0-beta.9-20230402
    # depends_on:
    #   tikv_cluster:
    #     restart: true
    #     condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 250M
    command: |
      start memory
      --user root
      --pass ${SURREAL_PASSWORD}
      --bind 0.0.0.0:${SURREAL_PORT}
    ports:
      - ${SURREAL_PORT}:${SURREAL_PORT}

  service_app:
    container_name: service_app
    image: service_app_dev
    build:
      context: .
      target: service-app
      dockerfile: dev.dockerfile
    depends_on:
      surrealdb:
        restart: true
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.10'
          memory: 100M
    healthcheck:
      test: curl --fail "http://localhost:$PORT/health" || exit 1
    environment:
      PORT: 3333
      TOKEN_KEY: ${TOKEN_KEY}
      SURREAL_HOST: surrealdb
      SURREAL_PORT: ${SURREAL_PORT}
      SURREAL_USER: root
      SURREAL_PASSWORD: ${SURREAL_PASSWORD}
    ports:
      - 3333:3333

volumes:
  tikv_cluster: null

networks:
  default:
    enable_ipv6: true
